### ISSUE TITLE
WSocket: StreamSubsription onError, onDone aren't honored

### ISSUE THREAD

**Issue by stevenosborne-wf** [Workiva/w_transport#134]
Consider the following setup: 
```dart
var socket =  await wt.WSocket.connect(
  _natsUri, 
  useSockJS: true, 
  sockJSProtocolsWhitelist: ['websocket', 'xhr-streaming'],
 sockJSTimeout: new Duration(seconds: 1)
);
var streamSub = socket.listen(
  _handleData,
  onError: _handleError,
  onDone: _handleDone
);
```

This will trigger the `_handleData`, `_handleError` and `_handleDone` callbacks appropriately. However, if I reassign the handlers
```dart
streamSub.onData(_newHandleData);
streamSub.onError(_newHandleError);
streamSub.onDone(_newHandleDone);
```
only the `onDone` handler is updated. i.e. lifecycle events and errors are still routed to `_handleDone` and `_handleDone` respectively.

**Comment by evanweible-wf** [comment]
@stevenosborne-wf after looking at this in more depth, the fix is going to require a bit of an overhaul internally with the way we wrap the underlying socket stream and sink. Shouldn't produce any API changes, but it is a bigger effort than I originally thought so I'm going to come back to it in a little while.
